### ISSUE TITLE
Logotipo & Interface para o @CivitasOrg

### ISSUE THREAD

**Issue by onhernandes** [designbrasil/Projetos-Aberto#2]
## CivitasOrg
Civitas é um projeto totalmente open-source(sem fins lucrativos!) que propõe criar uma aplicação para gerência de comunidades. A ideia é ter um lugar onde as pessoas consigam organizar eventos, ter controle de organizadores/co-organizadores/membros, palestrantes, apoiadores, patrocinadores e etc.

## Objetivo
Não há nenhum aplicativo que supra 100% as necessidades organizacionais das comunidades. Todo mundo desenvolve sua metodologia e usa N ferramentas pra gerenciar isso, e consequentemente, muita gente perde muito tempo com isso. Civitas pode não resolver tudo, e nem ajudar com tudo, mas fará o máximo possível pra melhorar isso.

## Skills necessários
- Vontade de ajudar
- UI/Logotipos(é basicamente o que precisamos)

Precisamos de ajuda para bolar o logotipo(pensamos em discutir num fórum sobre qual escolher), desenhar o site principal e o sistema interno.

## Projetos similares
O meetup.com é um projeto parecido, mas o foco dele é apenas em eventos e bem limitado em relação a funcionalidades.

## Contato

Pode ser por aqui, ou pelo e-mail: [civitas@hernandes.io](mailto:civitas@hernandes.io)

**Comment by eliezercardoso** [comment]
Hernandes, eu gostaria de ajudar.

**Comment by onhernandes** [comment]
@eliezercardoso a gente tem um grupo no Telegram: https://t.me/joinchat/IhFykBAChmmLEzwTnbbZYQ
